
SOURCES := $(shell find . -name *.c)
OBJS := $(SOURCES:%.c=%.o)

CFLAGS := -Wall -Wextra -Wpedantic -std=c99 -O3

jdedit: $(OBJS)
	gcc $(OBJS) -o jdedit

-include $(OBJS:.o=.d)

%.o: %.c
	gcc -c $(CFLAGS) $*.c -o $*.o
	gcc -MM $(CFLAGS) $*.c > $*.d
	@mv -f $*.d $*.d.tmp
	@sed -e 's|.*:|$*.o:|' < $*.d.tmp > $*.d
	@sed -e 's/.*://' -e 's/\\$$//' < $*.d.tmp | fmt -1 | \
	  sed -e 's/^ *//' -e 's/$$/:/' >> $*.d
	@rm -f $*.d.tmp

run: jdedit
	@./jdedit

clean:
	rm -f jdedit *.o *.d
